# Jean pockets

Are women jean pockets ridiculously small? Let's look at the data!

The file `jean-pocket-measurements.csv` shows pocket measurements for 20 popular brands.
Four pairs of jeans from each brand were measured: men's and women's skinny and straight styles. All jeans were designated a 32-inch waistband. 

The following measurements are included:
- `height_front`: maximum front pocket height (cm)
- `height_back`: maximum back pocket height (cm)
- `width_front`: maximum front pocket width (cm)
- `width_back`: maximum back pocket width (cm)

In [2]:
# FOR GOOGLE COLAB ONLY.
# Uncomment and run the code below. A dialog will appear to upload files.
# Upload 'jean-pocket-measurements.csv'.

# from google.colab import files
# uploaded = files.upload()

In [3]:
import pandas as pd
df = pd.read_csv('jean-pocket-measurements.csv')
df.head()

,brand,style,gender,height_front,width_front,height_back,width_back
0,3fe5003e,skinny,women,14.5,16.5,15.0,13.7
1,3fe5003e,straight,women,14.5,16.0,15.5,13.0
2,790c6eab,skinny,women,13.0,14.5,15.5,13.5
3,790c6eab,straight,women,13.0,14.5,14.5,13.0
4,26aaf627,skinny,women,13.0,14.0,14.0,14.2

### Project Ideas

- What is the average difference in pocket `height_front` between women's and men's jeans?

- Is there a significant difference in pocket `height_front` between skinny and straight styles within the same gender?

- How do back pocket sizes compare between women's and men's jeans?

- Measure your phone's height. What percentage of women's and men's jeans can comfortably fit your phone in the pockets?

### Solutions

To determine the average difference in pocket **height_from** between women's and men's jeans I am going to apply a **groupby()** and them calculate the average. Functions used:
- gropby(): To group by gender
- mean(): To calculate the average
- reset_index(): To convert a serie into dataframe
- query(): To search by gender

In [23]:
average_df=df.groupby('gender')['height_front'].mean().reset_index()

men_height = average_df.query('gender == "men"')['height_front'].values[0]
women_height = average_df.query('gender == "women"')['height_front'].values[0]
result = abs(men_height - women_height).round(2)

print(result)

8.8

The average different is 8.8 cm.

Now, I want to calculate the differente between skinny and straight styles, divided by gender

In [37]:
grouped_df = df.groupby(['gender', 'style'])['height_front'].mean().reset_index()

height_front_col_M = grouped_df.query('gender == "men"')['height_front']

height_front_col_W = grouped_df.query('gender == "women"')['height_front']

result_M = abs(height_front_col_M.values[0] - height_front_col_M.values[1])

result_W = abs(height_front_col_W.values[0] - height_front_col_W.values[1])

print("Pocket different between skinny and straight men pants: %.2f cm" %result_M)
print("Pocket different between skinny and straight women pants: %.2f cm" %result_W)

grouped_df

Pocket different between skinny and straight men pants: 0.11 cm
Pocket different between skinny and straight women pants: 0.12 cm

  gender     style  height_front
0    men    skinny        23.185
1    men  straight        23.075
2  women    skinny        14.270
3  women  straight        14.385

From previous calculation we can conclude that there isn't a big different in pockets between skinny and straight pants in both genders.

#### Back pockets

Find out the different in back pockets size between men and women

In [58]:
#area
df['area']=df.eval('height_back*width_back')

area_df = df.groupby('gender')['area'].mean().reset_index()

result = abs(area_df['area'].values[0]-area_df['area'].values[1])

print("Back pockets differents: %.2f cm" %result)

Back pockets differents: 17.89 cm

The different between back pockets is big.

Size of my cellphone

- height_cellphone = 16,5 cm
- width_cellphone = 8 cm

In [72]:
height_cellphone = 16.5
width_cellphone = 8

count_men = (df['gender']=='men').sum()

count_women =(df['gender']=='women').sum()

cell_df = df.query("height_back >= @height_cellphone and width_back >= @width_cellphone")

cell_men_count = (cell_df['gender']=='men').sum()

cell_women_count = (cell_df['gender']=='women').sum()

# %
men_comfort_pants = 100*(cell_men_count/count_men) 

women_comfort_pants = 100*(cell_women_count/count_women)

print(f"Only {int(men_comfort_pants)}% of men and {int(women_comfort_pants)}% of women can comfortably fit my phone in the pockets")

Only 35% of men and 10% of women can comfortably fit my phone in the pockets

From the previous result we can conclude that the major of pants cannot fit well in the pocket pants. And answering the initial question, my answer is "yes, the pockets in women pants are very small from my personal experience and because the last analysis confirm this fact.